spring.application.name=text-to-speech-backend

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

gemini.api.url=${GEMINI_API_URL}
gemini.api.key=${GEMINI_API_KEY}